version: "3"
networks:
  dinky_net:
    external: true
services:
  jobmanager:
    hostname: jobmanager
    container_name: jobmanager
    restart: always
    image: flink:${FLINK_VERSION}-scala_2.12-java8
    command: jobmanager
    environment:
      - HADOOP_CONF_DIR=/opt/flink/conf
    volumes:
      - ./conf:/opt/flink/conf
      - ./flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
    networks:
      - dinky_net
  taskmanager:
    hostname: taskmanager
    container_name: taskmanager
    image: flink:${FLINK_VERSION}-scala_2.12-java8
    command: taskmanager
    environment:
      - HADOOP_CONF_DIR=/opt/flink/conf
    volumes:
      - ./conf:/opt/flink/conf
      - ./flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
    networks:
      - dinky_net
    depends_on:
      - jobmanager
